### PR TITLE
Add workflows

### LINKED ISSUE #1: Pipeline and terraform file for python lambda

### PR DESCRIPTION
**Pull request by filipezz**

### CODE REVIEW

**Comment by filipezz** [comment]
test

**Comment by filipezz** [comment]
asbaba

**Comment by filipezz** [comment]
asbabaa

**Comment by filipezz** [comment]
asbabababa

**Comment by filipezz** [comment]
asbaba

**Comment by filipezz** [comment]
asbabula

**Comment by filipezz** [comment]
zxcc

**Comment by filipezz** [comment]
asbaba

**Comment by filipezz** [comment]
asbba

**Review by juniozguedes — APPROVED** [review]
lgtm! thank you

**Pull request merged**
